# Generated by Django 5.0.6 on 2024-06-07 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_genero', to='myapp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_mensaje', to='myapp.user')),
                ('id_user_matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_matched_mensaje', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_match_user', to='myapp.user')),
                ('id_user_matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_matched', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='myapp/static/img')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_foto', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('id_mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_mensaje_chat', to='myapp.mensaje')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_chat', to='myapp.user')),
                ('id_user_matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_matched_chat', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='myapp/static/img')),
                ('descripcion', models.TextField()),
                ('carrera', models.CharField(max_length=100)),
                ('id_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_settings_foto', to='myapp.foto')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_settings_genero', to='myapp.genero')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_settings', to='myapp.user')),
            ],
        ),
    ]
