# Generated by Django 5.0 on 2024-07-02 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('userMensaje_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMensaje_1', to='myapp.usuario')),
                ('userMensaje_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMensaje_2', to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMatch_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMatch_1', to='myapp.usuario')),
                ('userMatch_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMatch_2', to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='myapp/static/img')),
                ('usuarioFoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatMensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mensaje')),
                ('userChat_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userChat_1', to='myapp.usuario')),
                ('userChat_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userChat_2', to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='myapp/static/img')),
                ('descripcion', models.TextField()),
                ('carrera', models.CharField(max_length=100)),
                ('fotoConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.foto')),
                ('userConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
