# Generated by Django 5.0.6 on 2024-07-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestano', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='myapp.usuario')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='myapp.usuario')),
            ],
            options={
                'unique_together': {('liker', 'liked')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_by', through='myapp.Like', to='myapp.usuario'),
        ),
    ]
