# Generated by Django 5.0.6 on 2024-07-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_like_usuario_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosettings',
            name='fotoConfig',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
